version: '3'

tasks:
  test:
    cmds:
      - go test -race -mod=readonly ./...

  deps-upgrade:
    cmds:
      - go get -t -u ./...
      - go mod tidy

  lint:
    cmds:
      - golangci-lint run ./...

  install-deps:
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@v3.13.0
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2
      - go install github.com/golang/mock/mockgen@v1.6.0
