version: 2.1

executors:
  go:
    docker:
      - image: cimg/go:1.19

commands:
  restore-cache:
    steps:
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}-v1
      - restore_cache:
          keys:
            - go-bin-{{ checksum "Taskfile.yaml" }}-v1

jobs:
  setup:
    executor: go
    steps:
      - checkout
      - restore-cache
      - run: go install github.com/go-task/task/v3/cmd/task@latest
      - run: task install-deps
      - run: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}-v1
          paths:
            - "~/go/pkg/mod"
      - save_cache:
          key: go-bin-{{ checksum "Taskfile.yaml" }}-v1
          paths:
            - "~/go/bin"
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - go

  lint:
    executor: go
    steps:
      - attach_workspace:
          at: ~/
      - run: task lint

  test:
    executor: go
    steps:
      - attach_workspace:
          at: ~/
      - run: |
          mkdir -p /tmp/test-reports
          gotestsum --junitfile /tmp/test-reports/unit-tests.xml ./... -race
      - store_test_results:
          path: /tmp/test-reports

workflows:
  test-and-publish:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup








