version: 2.1

executors:
  go:
    docker:
      - image: cimg/go:1.17

commands:
  install-deps:
    steps:
      - run: echo "Hello <<parameters.to>>"

jobs:
  setup:
    executor: go
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: go install github.com/go-task/task/v3/cmd/task@latest
      - run: task install-deps
      - run: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  lint:
    executor: go
    steps:
      - attach_workspace:
          at: ~/project
      - run: task lint

  test:
    executor: go
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          mkdir -p /tmp/test-reports
          gotestsum --junitfile /tmp/test-reports/unit-tests.xml ./... -race
      - store_test_results:
          path: /tmp/test-reports

workflows:
  test-and-publish:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup








